# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Starting our demo
        run: echo Hello GSE UK!

      # Runs a set of commands using the runners shell
      - name: Install Zowe CLI and setup profile
        env:
          ZOSMF_HOST: ${{ secrets.zosmf_host }}
          ZOSMF_PORT: ${{ secrets.zosmf_port }} 
          ZOSMF_USER: ${{ secrets.zosmf_user }}
          ZOSMF_PSW:  ${{ secrets.zosmf_psw }}
        run: |
          node --version
          npm install -g @zowe/cli@zowe-v1-lts
          zowe --version
          zowe profiles cre zosmf-profile GSE --user $ZOSMF_USER --password $ZOSMF_PSW --host $ZOSMF_HOST --port $ZOSMF_PORT --reject-unauthorized false
          echo "Files to upload"
          ls -al JCL
          zowe zos-files upload dir-to-pds "JCL" "Z01774.GSE.JCL"

